DROP TABLE IF EXISTS Students;
CREATE TABLE Students(
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL,
    age TINYINT NOT NULL,
    created_at TIMESTAMP NOT NULL
)